version: "3.9"

services:
  hotel-booking-postgres:
    image: postgres:18
    container_name: hotel-booking-postgres
    restart: unless-stopped

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: hotel-booking-db

    ports:
      - "5432:5432"

    volumes:
      - hotel-booking-postgres-data:/var/lib/postgresql

  hotel-booking-keycloak-postgres:
    image: postgres:18
    container_name: hotel-booking-keycloak-postgres
    restart: unless-stopped

    environment:
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
      POSTGRES_DB: keycloak

    ports:
      - "5433:5432"

    volumes:
      - hotel-booking-keycloak-postgres-data:/var/lib/postgresql

  hotel-booking-keycloak:
    image: quay.io/keycloak/keycloak:26.2
    container_name: hotel-booking-keycloak
    restart: unless-stopped

    command:
      - start-dev

    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: hotel-booking-keycloak-postgres
      KC_DB_URL_PORT: 5432
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak

      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin

      KC_HTTP_PORT: 8080

    ports:
      - "8180:8080"

    depends_on:
      - hotel-booking-keycloak-postgres

volumes:
  hotel-booking-postgres-data:
  hotel-booking-keycloak-postgres-data: